# Generated by Django 6.0.3 on 2026-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_hp', models.IntegerField(default=100)),
                ('player_attack', models.IntegerField(default=10)),
                ('player_level', models.IntegerField(default=1)),
                ('player_x', models.IntegerField(default=0)),
                ('player_y', models.IntegerField(default=0)),
                ('map_data', models.JSONField(default=dict)),
                ('log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
